name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Kør workflow, når der pushes til main-grenen

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Tjek koden ud fra repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Opsæt Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Brug en kompatibel version af Node.js

      # Installer afhængigheder
      - name: Install dependencies
        run: npm install

      # Byg projektet
      - name: Build project
        run: npm run build

      # Deploy til GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Mappen, der skal deployes